spring:
  application:
    name: Hello Boot
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@${ORACLE_HOST:localhost}:1521:free
    username: testuser
    password: testpwd
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    enabled: true

management:
  data:
    generation:
      enabled: false